# Generated by Django 4.0.2 on 2022-02-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesArea',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('geojson', models.CharField(max_length=100)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restapi.servicesarea')),
            ],
        ),
    ]
