# Generated by Django 4.0.2 on 2022-02-25 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesarea',
            old_name='student_id',
            new_name='service_id',
        ),
    ]
